// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calccaaC
NumericMatrix calccaaC(NumericVector pars, NumericMatrix pnaa, double M, NumericVector sel, NumericVector ages);
RcppExport SEXP _fmr_calccaaC(SEXP parsSEXP, SEXP pnaaSEXP, SEXP MSEXP, SEXP selSEXP, SEXP agesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pnaa(pnaaSEXP);
    Rcpp::traits::input_parameter< double >::type M(MSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sel(selSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ages(agesSEXP);
    rcpp_result_gen = Rcpp::wrap(calccaaC(pars, pnaa, M, sel, ages));
    return rcpp_result_gen;
END_RCPP
}
// calcnaaC
List calcnaaC(NumericVector pars, double M, NumericVector yrs, NumericVector ages, NumericMatrix owa);
RcppExport SEXP _fmr_calcnaaC(SEXP parsSEXP, SEXP MSEXP, SEXP yrsSEXP, SEXP agesSEXP, SEXP owaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< double >::type M(MSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yrs(yrsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ages(agesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type owa(owaSEXP);
    rcpp_result_gen = Rcpp::wrap(calcnaaC(pars, M, yrs, ages, owa));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fmr_calccaaC", (DL_FUNC) &_fmr_calccaaC, 5},
    {"_fmr_calcnaaC", (DL_FUNC) &_fmr_calcnaaC, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_fmr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
