



#' @title plotASPM plots catch, CPUE, Spawning Biomass and Harvest Rate
#' 
#' @description plotASPM after running fitASPM the optimum parameters can be 
#'     put through the dynamics function to generate a dataframe containing
#'     the optimum dynamics. These can be plotted using plotASPM, which plots
#'     out the catches, the Spawning Biomass, the relative CPUE and its fit to
#'     the observed CPUE, and the harvest rate. This routine is still under 
#'     development to include more options.
#'
#' @param infish an object generated by the dynamics function
#' @param CI defaults to NA, if confidence intervals around the cpue have been
#'     obtained using getLNCI, then the resulting matrix will generate 95pc CIs 
#' @param target target depletion level. Defaults to 0.48
#' @param usef defines the font to use usef(ont),default = 7 bold times
#' @param rundir default '', otherwise give a full path if saving a file
#' @param console default=TRUE, which implies the plot will go to console. If
#'     set TRUE it will save pathtopath(rundir,'scenario.png')
#' @param scenario default = '', but if a file is to be saved then this should\
#'     be given a name for the file, if left as '', then it will be called 
#'     ASPM.png
#' @param maxy default = 0, which means use the data to set ymax. If maxy > 0
#'     the ymax will be set to that value. Used to allow details to be seen
#'
#' @return Nothing, but it does plot six graphs in a single plot.
#' @export
#'
#' @examples
#' require(fmr)
#' data(westroughy)
#' fish <- westroughy$fish
#' glb <- westroughy$glb
#' props <- westroughy$props
#' pars <- c(7.1,-1,-7.7)  # logR0 logceSE logavq
#' bestaspm <- fitASPM(pars,minfun=dynamicsH,infish=fish,
#'                    inglb=glb,inprops=props)
#' out <- dynamicsH(bestaspm$estimate,fish,glb,props,full=TRUE)
#' plotASPM(out$fishery, console=TRUE)
#' ceCI <- getLNCI(out$fishery[,"predCE"],exp(bestaspm$estimate[2]))
#' plotASPM(out$fishery,CI=ceCI, console=TRUE)
#' # infish=fishery; CI=ceCI;defineplot=TRUE; target=0.48; usef=7;rundir=""
#' # console=TRUE; scenario=""; maxy=10
plotASPM <- function(infish,CI=NA,target=0.48,usef=7,
                     rundir="",console=TRUE,scenario="",maxy=0) { 
  filen <- ""
  if (!console) {
    if (nchar(scenario) == 0) scenario <- "ASPM" 
    filen <- pathtopath(rundir,paste0(scenario,".png"))
  }
  plotprep(width=7, height=5.5,filename=filen,verbose=FALSE)
  parset(plots=c(3,2),margin=c(0.25,0.4,0.1,0.05),cex=0.85,font=usef)
  yrs <- infish$year
  nyrs <- length(yrs)
  # plot catches
  ymax <- getmax(infish$catch)
  plot(yrs,infish$catch,type="l",lwd=2,ylim=c(0,ymax),yaxs="i",xlab="",
       panel.first=grid(),ylab="Catch (t)")
  # plot Spawning Biomass
  ymax <- getmax(infish$spawnB)
  plot(yrs,infish$spawnB,type="l",lwd=2,ylim=c(0,ymax),yaxs="i",xlab="",
       panel.first=grid(),ylab="Spawning Biomass (t)")
  # plot CPUE
  ymax <- getmax(c(infish$cpue,infish$predCE))
  if ("matrix" %in% class(CI)) ymax <- getmax(CI[,"upper"]) 
  if (maxy > 0) ymax <- maxy
  plot(yrs,infish$cpue,type="p",pch=16,col=2,cex=1.0,ylim=c(0,ymax),yaxs="i",
       xlab="",panel.first=grid(),ylab="Relative Abundance Index")
  lines(yrs,infish$predCE,lwd=2,col=1)
  if ("matrix" %in% class(CI)) {
    segments(x0=yrs,y0=CI[,1],x1=yrs,y1=CI[,3],lwd=1,col=4)
  }
  # plot harvest rate
  ymax <- getmax(infish$fullH)
  if (!is.null(infish$fullF)) ymax <- getmax(c(infish$fullH,infish$fullF))   
  plot(yrs,infish$fullH,type="l",lwd=2,ylim=c(0,ymax),yaxs="i",xlab="",
       panel.first=grid(),ylab="Annual Rate")
  if (!is.null(infish$fullF)) {
    lines(yrs,infish$fullF,lwd=2,col=2)
    legend("topleft",c("Harvest","InstantF"),col=c(1,2),lwd=3,bty="n",cex=1.0)
  }   
  # plot the residuals
  pickCE <- which(infish[,"cpue"] > 0)
  resid <- log(infish[pickCE,"cpue"]/infish[pickCE,"predCE"])
  nresid <- length(resid)
  ymax <- getmax(resid);    ymin <- getmin(resid,mult=1.1)
  plot(yrs[pickCE],resid,"n",ylim=c(ymin,ymax),ylab="LogN Residuals",xlab="")
  grid()
  abline(h=0.0,col=1)
  segments(x0=yrs[pickCE],y0=rep(0.0,nresid),x1=yrs[pickCE],y1=resid,lwd=2,col=2)
  points(yrs[pickCE],resid,pch=16,col=1,cex=1.0)
  rmseresid <- sqrt(sum(resid^2)/nresid)
  text(min(yrs[pickCE]),ymin*0.85,paste("rmse = ",round(rmseresid,3),sep=""),
       font=7,cex=1.0,pos=4)
  # plot the depletion level
  ymax <- getmax(infish$deplete)
  plot(yrs,infish$deplete,type="l",lwd=2,ylim=c(0,ymax),yaxs="i",xlab="",
       panel.first=grid(),ylab="Depletion")
  abline(h=c(0.2,target),col=c(2,3),lwd=1)
  text(yrs[nyrs-1],0.9,round(infish$deplete[nrow(infish)],3),cex=1.0)
  if (!console) dev.off()
  return(invisible(filen))
} # end of plotASPM

#' @title plotceASPM plots just the fit of the ASPM model to the CPUE data
#' 
#' @description plotceASPM plots just the fit of the ASPM model to the CPUE data
#'     and provides a more detailed visual than plotASPM. It has the option of 
#'     including lognormal confidence intervals around the predcted CPUE.
#'
#' @param infish output from the dynamics function using the optimum parameters
#' @param CI the output matrix from getLNCI function. Needs to have the lower CI
#'    in column 1 and the upper CI in the third column.
#' @param defineplot defaults to TRUE, determines whether to set up an new 
#'     graphics window.
#'
#' @return returns nothing but does plot a graph
#' @export
#'
#' @examples
#' data(westroughy)
#' fish <- westroughy$fish
#' glb <- westroughy$glb
#' props <- westroughy$props
#' pars <- c(7.1,-1,-7.7)
#' bestaspm <- fitASPM(pars,minfun=dynamicsH,infish=fish,
#'                     inglb=glb,inprops=props)
#' out <- dynamicsH(bestaspm$estimate,fish,glb,props,full=TRUE)
#' ceCI <- getLNCI(out$fishery[,"predCE"],exp(bestaspm$estimate[2]))
#' plotceASPM(out$fishery,CI=ceCI)
plotceASPM <- function(infish,CI=NA,defineplot=TRUE) { 
  # infish=out$fishery; CI=ceCI; defineplot=TRUE
  if (defineplot) { 
    if (names(dev.cur()) %in% c("null device", "RStudioGD"))
      dev.new(width = 7, height = 4.5, noRStudioGD = TRUE)
  } 
  par(mfrow=c(1,1),mai=c(0.4,0.5,0.1,0.05),oma=c(0.0,0,0.0,0.0)) 
  par(cex=1.0, mgp=c(1.35,0.35,0), font.axis=7,font=7,font.lab=7,tck=-0.02)  
  yrs <- infish$year
  if (inherits(CI,"matrix")) { 
    confint <- CI[,3]
  } else {   
    confint <- NA  
  }
  ymax <- getmax(c(infish$cpue,infish$predCE,confint))
  plot(yrs,infish$cpue,type="p",ylim=c(0,ymax),yaxs="i",
       xlab="",panel.first=grid(),ylab="Relative CPUE")
  if (inherits(CI,"matrix")) {
    arrows(x0=yrs,y0=CI[,1],x1=yrs,y1=CI[,3],code=3,length=0.03,angle=90,
           lwd=1,col=4)
  }   
  points(yrs,infish$cpue,pch=16,col=2,cex=1.0)     
  lines(yrs,infish$predCE,lwd=2,col=1)
} # end of plotceASPM

#' @title plotdynfish generates a plot of a fisheries dynamics
#' 
#' @description plotdynfish generates a plot of a fisheries dynamics. This 
#'     includes plots of predicted CPUE vs observed CPUE, the residuals for the
#'     same (separate plots for different gears), the spawning biomass 
#'     depletion, the recruitment levels, the catches, and the instantaneous
#'     F levels
#'
#' @param outfish a data.frame of the fishery dynamics, as a minimum it must 
#'     obviously include observed and predicted catches and CPUE, spawning
#'     biomass depletion, recruitment, and instantaneous F values. The column
#'     headings of which can be identified in teh columns argument, in which
#'     the order is important.
#' @param console should the plot go to the console, default = TRUE
#' @param prepplot should the plotprep function be used? default = TRUE
#' @param addtitle The default filename if 'fishery_dynamics.png' use addtitle
#'     to add text in front of that. eg addtitle='Speciesname_'
#' @param rundir the directory into which to save the file if console=FALSE,
#'     default = ''
#' @param width the width of the plot within plotprep if used, default=8
#' @param height the height of the plot within plotprep if used, default=7
#' @param nfleet default = 2, determines how many gears are expected can only
#'     be 1 or 2. If nfleet = 1 consider reducing height
#' @param obsdata default = TRUE. To plot CPUE residuals the observed CPUE is 
#'     required. When plotting simulated data there are no 'observed' so set
#'     obsdata to FALSE, which omits the residual plots. 
#' @param year character name of the year column, default ='year'
#' @param recruit character name of the recruitment column, the predrec column
#'     contains the predicted recruitment without the deviate value. default =
#'     'recruit' and 'predrec'. If no predrec values leave as default
#' @param depl character name of the spawning biomass depletion column default 
#'     = 'deplsB'
#' @param gears character names of the fishing gear names, not columns.
#'     default = 'Trawl' and 'Autoline'
#' @param catch character names of the catches columns. default = 'twl',"auln 
#' @param instF character name of the ycolumns containing the estimates of 
#'     instantaneous F for each gear through time. default='twlPF', 'aulnPF"
#' @param cecols character name of the column of cpue information, predicted
#'     values for each gear followed by the observed values for that gear (if
#'     present). default = 'twlPCE','twlCE','aulnPCE','aulnCE'
#'
#' @returns nothing but it does generate a plot
#' @export
#'
#' @examples
#' print("Wait on example data - again")
#' print("Can now plot simulated dynamics")
plotdynfish <- function(outfish,console=TRUE,addtitle="",prepplot=TRUE,
                        rundir="",width=8,height=7,nfleet=2,obsdata=TRUE,
                        year="year",recruit=c("recruit","predrec"),
                        depl="deplsB",gears=c("Trawl","Autoline"),
                        catch=c("twl","auln"),instF=c("twlPF","aulnPF"),
                        cecols=c("twlPCE","twlCE","aulnPCE","aulnCE")) {
  # outfish=outFD$fishery;console=TRUE;addtitle="";prepplot=TRUE;
  # rundir="";width=8;height=7;nfleet=1;obsdata=TRUE
  # columns=c("year","twl","twlCE","twlPCE","deplsB","recruit","twlPF","Trawl")
  
  # outfish=outIA$fishery;console=TRUE;addtitle="";prepplot=TRUE;rundir=""
  #              width=8;height=7;nfleet=1;obsdata=TRUE
  #              year="year";recruit=c("recruit","predrec")
  #              depl="deplete";gears=c("Trawl");catch=c("twl");instF=c("fullF") 
  #              cecols=c("twlPCE","twlCE"); 
  
  oldpar <- par(no.readonly=TRUE)
  on.exit(par(oldpar))
  fishery <- replacezeros(outfish)
  yrs <- fishery[,year]
  if (console & prepplot) {
    plotprep(width=width,height=height,cex=1.0,filename="",verbose=FALSE)
  } else {
    filen <- pathtopath(rundir,paste0(addtitle,"fishery_dynamics.png"))
    plotprep(width=width,height=height,cex=1.0,newdev=TRUE,filename=filen,
             verbose=FALSE)
  }
  if ((nfleet == 1) || (!obsdata)) {
    parset(plots=c(3,2),margin=c(0.3,0.4,0.05,0.05),byrow=FALSE)
  } else {
    parset(plots=c(4,2),margin=c(0.3,0.4,0.05,0.05),byrow=FALSE)
  }
  if (obsdata) {
    maxy <- getmax(fishery[,cecols[1:2]])
  } else { 
    maxy <- getmax(fishery[,cecols[1]]) 
  }
  plot(yrs,fishery[,cecols[1]],type="l",lwd=2,col=1,
       ylab=paste0(gears[1]," CPUE"),ylim=c(0,maxy),yaxs="i",xlab="",
       panel.first=grid())
  if (obsdata) {
    points(yrs,fishery[,cecols[2]],pch=16,cex=1.1,col=2)
    lines(yrs,fishery[,cecols[2]],lwd=1,col=2,lty=3)
  }
  if ((nfleet > 1) & (obsdata)) {
    legend("topright",c("Predicted","Observed"),col=c(1:nfleet),lwd=3,bty="n",
           cex=1.2)
  }
  if (nfleet == 2) {  # could generalize to nfleet > 2 with loop here
    if (obsdata) { 
      usece <- fishery[,cecols[3:4]]
      maxy <- getmax(usece)
    } else { 
      usece <- fishery[,cecols[2]]
      maxy <- getmax(usece) 
    }
    plot(yrs,usece[,1],type="l",lwd=2,col=1,
         ylab=paste0(gears[2]," CPUE"),
         ylim=c(0,maxy),yaxs="i",xlab="",panel.first=grid())
    if (obsdata) {
      points(yrs,usece[,2],pch=16,cex=1.1,col=2)
      lines(yrs,usece[,2],lwd=1,col=2,lty=3)
    }
  }
  maxy <- getmax(fishery[,depl])
  plot(yrs,fishery[,depl],type="l",lwd=2,col=1,ylab="Spawning Depletion",
       ylim=c(0,maxy),yaxs="i",xlab="",panel.first=grid())
  abline(h=c(0.4,0.2),lwd=c(1,1),col=c(3,2))
  maxy <- getmax(fishery[,recruit[1]])
  plot(yrs,fishery[,recruit[1]],type="l",lwd=2,col=1,ylab="Recruitment",
       ylim=c(0,maxy),yaxs="i",xlab="",panel.first=grid())
  if (length(fishery[,recruit[2]]) > 0) {
    lines(yrs,fishery[,recruit[2]],lwd=2,col=2)
  }
  if (obsdata) {
    twlresid <- fishery[,cecols[2]]/fishery[,cecols[1]]    
    maxy <- getmax(twlresid); miny <- getmin(twlresid)
    plot(yrs,twlresid,type="p",pch=16,col=1,cex=1,
         ylab=paste0(gears[1]," CPUE Residuals"),
         ylim=c(miny,maxy),yaxs="i",xlab="",panel.first=grid())
    lines(yrs,twlresid,lwd=1,col=2,lty=2)
    abline(h=1,lwd=1,col=1)
  }
  if ((nfleet == 2) & (obsdata)) {
    usece <- fishery[,cecols[3:4]]
    aulnresid <- usece[,2]/usece[,1]
    maxy <- getmax(aulnresid); miny <- getmin(aulnresid)
    plot(yrs,aulnresid,type="p",pch=16,col=1,cex=1,
         ylab=paste0(gears[2]," CPUE Residuals"),
         ylim=c(miny,maxy),yaxs="i",xlab="",panel.first=grid())
    lines(yrs,aulnresid,lwd=1,col=2,lty=2)
    abline(h=1,lwd=1,col=1)
  }
  if (nfleet == 2) {
    totC <- rowSums(fishery[,c(catch)],na.rm=TRUE)
    totC[which(totC == 0)] <- NA
    maxy <- getmax(totC)
  } else {
    maxy <- getmax(fishery[,catch[1]])
  }
  plot(yrs,fishery[,catch[1]],type="l",lwd=2,col=1,ylab="Catches (t)",
       ylim=c(0,maxy),yaxs="i",xlab="",panel.first=grid())
  if (nfleet == 2) {
    lines(yrs,fishery[,catch[2]],lwd=2,col=2)
    lines(yrs,totC,lwd=2,col=4)
    legend("topleft",c(gears,"Total"),col=c(1,2,4),lwd=3,bty="n",
           cex=1.1)
  }
  maxy <- getmax(fishery[,c(instF)])
  plot(yrs,fishery[,instF[1]],type="l",lwd=2,col=1,ylab="Instantaneous F",
       ylim=c(0,maxy),yaxs="i",xlab="",panel.first=grid())
  if (nfleet == 2) {
    lines(yrs,fishery[,instF[2]],lwd=2,col=2)
    legend("topleft",c(gears),col=c(1:nfleet),lwd=3,bty="n",cex=1.1)
  }
} # end of plotdynfish



#' @title plotprops generates a 2x2 plot of the fishery properties
#' 
#' @description plotprops generates a 2 x 2 plot of the fishery properties of
#'     the length-at-age, maturity-at-age, weight-at-age, and selectivity-at-age
#'
#' @param rundir the directory in which the analysis is being run
#' @param props the matrix of fishery properties including laa, waa, maa, and 
#'     sela in columns 2 - 5 
#' @param console should the plot go to the console or be saved as a png file
#'     into rundir? default=TRUE ie plot to console
#'
#' @return thefilen used, which defaults '', but generates a plot
#' @export
#'
#' @examples
#' data("westroughy")
#' plotprops(rundir="",westroughy$props,console=TRUE)
#' # rundir=rundir; props=props; console=TRUE
plotprops <- function(rundir,props,console=TRUE) {
  filen <- "" 
  if (!console)  filen <- pathtopath(rundir,"fishery_properties.png")
  label <- c("Length-at-Age","Weight-at-Age","Maturity-at-Age",
             "Selectivity-at-Age")  
  numcol <- ncol(props)
  ages <- props[,"age"]
  plotprep(width=9, height=7,filename=filen,verbose=FALSE)
  parset(plots=c(2,2),margin=c(0.25,0.5,0.1,0.1),outmargin=c(1,0,0,0))
  for (i in 2:4) {
    maxy <- getmax(props[,i])
    plot(ages,props[,i],type="l",lwd=3,xlab="",ylab=label[i-1],ylim=c(0,maxy),
         yaxs="i",panel.first=grid())
  }
  mtext("Age Years",side=1,line=-0.1,outer=TRUE,cex=1.1)
  if (numcol == 5) {
    plot(ages,props[,numcol],type="l",lwd=3,xlab="",ylab=label[4],
         panel.first=grid())
  } else {
    fleets <- colnames(props)
    maxy <- getmax(props[,5])
    plot(ages,props[,5],type="l",lwd=3,xlab="",ylab=label[4],
         ylim=c(0,maxy),yaxs="i",panel.first=grid())
    for (flt in 6:numcol) lines(ages,props[,flt],lwd=3,col=(flt-4))
    legend("bottomright",fleets[5:numcol],col=c(1:(numcol-4)),lwd=3,
           cex=1.2,bty="n")
  }
  return(invisible(filen))
} # end of plotprops
