# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title calccaaC calculates the predicted catch-at-age
#'
#' @description calccaaC calculate the expected catch-at-age for a 
#'     statistical catch-at-age model. Implemented in Rcpp.
#'
#' @param pars a vector of log-transformed parameters
#' @param pnaa the predicted numbers-at-age in the population
#' @param M the natural mortality instantaneous rate
#' @param sel the selectivity at age
#' @param ages a vector identifying the ages being considered
#' @export
calccaaC <- function(pars, pnaa, M, sel, ages) {
    .Call(`_fmr_calccaaC`, pars, pnaa, M, sel, ages)
}

#' @title calcnaaC calculates the predicted numbers-at-age and exploitable B
#'
#' @description calcnaaC calculates the expected numbers-at-age, the 
#'     exploitable-numbers-at-age, the exploitable biomass by year, and the
#'     selectivity for a statistical catch-at-age model. Implemented in Rcpp.
#'
#' @param pars a vector of log-transformed parameters
#' @param M the natural mortality instantaneous rate
#' @param yrs is a vector of the years
#' @param ages a vector identifying the ages being considered
#' @param owa is a matrix of the observed weight-at-age
#' @export
calcnaaC <- function(pars, M, yrs, ages, owa) {
    .Call(`_fmr_calcnaaC`, pars, M, yrs, ages, owa)
}

